### ISSUE TITLE
Add some basic autocompletion

### ISSUE THREAD

**Issue by CalLavicka** [CalLavicka/c0-vscode-extension#1]
Using the LSP and the abstract syntax tree we have, we can provide autocompletion. Here are some ideas:

- Variable names
- Struct fields
- Function names
- Built-in functions (alloc, alloc_array)
- Contracts (requires, ensures, assert, loop_invariant)

Ideally, these would be somewhat context sensitive, so

- While inside a function, we don't suggest variables from a separate function.
- When using -> or ., we suggest fields, not variable names (and vice-versa). Bonus points for suggesting the correct fields based on the type of struct (hard).
- When after a //@, suggest appropriate contract name (so requires/ensures if after a function header, loop_invariant if after a loop, and assert otherwise).

This would entail:

- Creating and maintaining a list of symbols after typechecking for variables/struct fields.
- As the user types, we read what they have typed and look for symbols with that prefix.
- Using the VSCode LSP, we suggest the various suggestions back to the client from the server.

**Comment by ishantheperson** [comment]
My thoughts are to try to parse the document without the line the user is currently typing on, and then use that context information for each gdecl to suggestion things. We can probably hack something together based on what tokens we detect before the cursor. The lexer should be flexible enough to handle it...

**Comment by ishantheperson** [comment]
Mostly implemented by 8825e6455e314b54815db7b6fe2119dc13fe6f1b
