### ISSUE TITLE
Declare function as implementation-only

### ISSUE THREAD

**Issue by ishantheperson** [CalLavicka/c0-vscode-extension#17]
It would be cool to be able to mark a function as being part of an implementation, which means that it wouldn't be visible in code completion outside of that file

This could be done by modifying `restrictDeclaration` in `restrictsyntax.ts` 

```c
#implementation 

bool is_hdict(hdict* H) { 
 // ...
}
```

**Comment by kopecs** [comment]
Is there any reason to support adding a directive instead of just having students use header files for this purpose? I know we currently wait until introducing C to introduce header files but is introducing a directive really any better than just teaching header files a bit earlier?

**Comment by ishantheperson** [comment]
Header files kind of suck. The #interface pragma is analogous to the JavaScript "export" keyword or like declaring something "public" in an OO language.

**Comment by kopecs** [comment]
My main concern with having a pragma instead of using header files initially isn't so much that it wouldn't have analogs in other languages as it is that that's just not how C does it, so when we do switch to header files (without said pragma(s)) there'd be additional confusion.

To my understanding, `cc0` supports header files already so there's no need to change anything for compilation whereas this requires changes there (albeit, fairly insignificant ones). If the language server isn't already handling header files how does/would completion from C implemented libraries work? Support for header files seems to be a necessary feature.

**Comment by ishantheperson** [comment]
That's a good point about how C. I meant that with header files people would either have to manually specify the header for each file in project.txt and the command line, or the compiler would have to try to figure it out.

That is a good point about how it doesnt have an analog in C. Maybe this could just be used for starter code we give them, so it wouldn't be something students would write on their own (it would just be used to provide warnings)

**Comment by kopecs** [comment]
I think in the broader context it might just be better to replace project.txt with either a Makefile or something more analogous.

Regardless, if we plan on supporting code brought into scope by `#use` that wouldn't be part of the compilation command (or listed in project.txt), e.g., conio.h0 then it seems logical to me to just resolve that based on `#use`s in that translation unit.

**Comment by ishantheperson** [comment]
#use "foo.c0" is supported. People just can't use it because sometimes on Autolab we swap files (e.g. substitute pixel-array.c0 for pixel.c0) and #use "pixel.c0" would break that 

If you mean that project.txt should be more sophisticated and allow for multiple targets, that's definitely true and it would be great if you could implement that, otherwise I'll prob do it eventually

**Comment by kopecs** [comment]
If you just have the pixel interface in pixel.h0 instead, you can just have `#use "pixel.h0"` and compile against either; swapping files isn't actually an issue so long as you're including the header (which is what you ought to do regardless).

**Comment by ishantheperson** [comment]
That's a pretty good idea. That's a fairly large change to our curriculum so you'd need to discuss it with Iliano.

**Comment by ishantheperson** [comment]
Iliano said that a functional should be considered "exported" from a file if it has a separate declaration. He's also against using pragmas without changing the language. This means we'll have to wait on this one
