### ISSUE TITLE
Extension breaks with paths that contain parentheses on Mac

### ISSUE THREAD

**Issue by SiddharthParatkar** [CalLavicka/c0-vscode-extension#40]
When opening a file which relies on another file in a directory with parentheses in its path, the file fails to parse.

**Comment by ishantheperson** [comment]
I think it's something to do with this line

https://github.com/CalLavicka/c0-vscode-extension/blob/d9786629474d35589379c1c3ff22cc19e5371f4f/server/src/parse.ts#L295

We need to be able to handle arbitrary URL encoded sequences

**Comment by ishantheperson** [comment]
This seems useful https://github.com/microsoft/vscode/blob/master/src/vs/base/common/uri.ts

**Comment by ishantheperson** [comment]
The problem is that in the cache, we sometimes add the URI-encoded version of the path and sometimes add the regular string. This inconsistency can cause a file to be loaded twice, which can then cause compilation to mysteriously fail

**Comment by ishantheperson** [comment]
Should be fixed now, need to test on windows

**Comment by ishantheperson** [comment]
Fixed on both windows/mac
